SimpleWebDI/Controllers/RecipeController.cs
using System;
using System.Web.Mvc;
using RStein.Cookbook.Business.BusinessServices;
using RStein.Cookbook.Business.Core;
using SimpleUIFacade;
using SimpleWebDI.Models;

namespace SimpleWebDI.Controllers
{
  public class RecipeController : Controller
  {
    private readonly IRepository<Recipe> m_repository;
    private readonly RecipeUIFacade m_uiFacade;

    public RecipeController(IRepository<Recipe> repository, RecipeUIFacade uiFacade)
    {
      if (repository == null)
      {
        throw new ArgumentNullException("repository");
      }

      if (uiFacade == null)
      {
        throw new ArgumentNullException("uiFacade");
      }


      m_repository = repository;
      m_uiFacade = uiFacade;
    }

    public ActionResult Index(int page = 0)
    {
      const int PAGE_SIZE = 10;
      if (page < 0)
      {
        throw new ArgumentException("page");
      }

      var pager = new SimplePaginator<Recipe>(m_repository, page, PAGE_SIZE);
      return View(pager);
    }

    public ActionResult ExportAllRecipes()
    {
      m_uiFacade.ExportAllRecipes();
      return View();
    }
  }
}

SimpleWebDI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>MS Fest recepty</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Recepty", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Recepty", "Index", "Recipe")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - MS Fest Recepty</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>